# Generated by Django 5.1.6 on 2025-03-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='back',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='front',
        ),
        migrations.AddField(
            model_name='note',
            name='type',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
