# Generated by Django 5.1.6 on 2025-03-24 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_content_note_back_rename_title_note_front_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='front',
            new_name='title',
        ),
    ]
